server:
  port: 8086
spring:
  application:
    name: service-hi
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://116.62.41.101:8083/eureka/
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
xx: lili
